### ISSUE TITLE
Week #12: More FUSE Progress

### ISSUE THREAD

**Issue by tstamler** [gw-sd-2016/harddrivecache#2]
@cctoombs @twood02

This week, I made some more progress with the FUSE system. Before the presentation on Wednesday, I got the SSD mounted and got the basic caching policies working. The FUSE filesystem now adds files to the cache whenever it sees fit. Since the presentation on Wednesday, it now will automatically create necessary directories that do not exist on the hard drive, which had to be done manually. I also made it so that files can be easily deleted from the SSD, and made it so that any files that are deleted on the hard drive are also deleted on the SSD.

**Comment by twood02** [comment]
sounds like you are making good progress on the basic mechanics.

Before too long you will need to shift some of your focus to the algorithmic side---what should you cache if space is limited and several workloads are running simultaneously?  Since you've shifted to FUSE, which works at the file-level, you may not be able to reuse the MultiCache paper ideas as easily since it makes assumptions like accesses are at the block level and thus all of equal size.

**Comment by twood02** [comment]
also I've adjusted your week numbering scheme to make it consistent with other students.  Forget what you learned in grade school and think of Sundays as being the end of a week.
